### PR TITLE
Fixes #490

### LINKED ISSUE #490: VIAME-Dive JSON file vs folder named .JSON [BUG]
**Describe the bug**
Notice in I believe both windows and linux if you download everything from server it could include a folder named resuly_{timestampt}.json.  This prevents it from loading properly in VIAME-Dive
**To Reproduce**
1.  Download data from the web version which contains a json file.  Make sure you download everything
2. There should be a folder in there if with the name of `result_{timestamp}.json`
3.  This should prevent the viewer from loading properly.

**Expected behavior**
should properly ignore directories even if they are named with a `.json` inside of them.
**Desktop (please complete the following information):**
 - OS: I believe windows and linux

**Additional context**
I think this should be a simple fix.

### PR DESCRIPTION
**Pull request by subdavis**
Adds a loading spinner to show before track data has loaded, when you'd currently see a black page.  For large datasets and slow networks, this can be a long time.

fixes #490

### CODE REVIEW

File: client/platform/desktop/backend/platforms/common.ts [hunk 1]
```diff
@@ -63,6 +61,13 @@ async function getDatasetBase(datasetId: string): Promise<{
     return false;
   });
 
+  const jsonFileCandidates = await contents
+    .filter((name) => JsonFileName.test(name))
+    .filter(async (name) => {
+      const statResult = await fs.stat(npath.join(datasetFolderPath, name));
+      return statResult.isFile();
+    });
```
Comment (BryonLewis) [inline client/platform/desktop/backend/platforms/common.ts:69]: I'm having some issues with this, I'm guessing an async filter might need to be done differently?  Something like creating a map of all the promises and awaiting on them and then filtering once they're complete?  From my testing it looks like it doesn't await for the second filtering to be done before continuing on.

**Review by BryonLewis — CHANGES_REQUESTED** [review]
I think the async filtering may need to be done differently.

**Review by BryonLewis — APPROVED** [review]
Looks good, like how the error catching will catch issues with the JSON file parsing as well and display them to the user.
