### PR TITLE
Minor ui fixes

### LINKED ISSUE #278: In pipelines list change Utility to Utilities and place at bottom of list
Saw this on bryon's screen but ideally since detectors and trackers is plural, so should utilities, also problaly want detectors, trackers, then utilities

### LINKED ISSUE #388: [BUG] Edit icons near mouse cursors are distracting and confusing
Not sure how you all feel, but I feel that it (a) blocks content behind it (b) just servers as a distraction because there are now 2 things near the cursor. While not critical, my preference would be to remove them unless I'm outvoted here.

Simulatenously the pencil drawing one is confusing because you're not actually drawing anything new just editing.

### LINKED ISSUE #409: [BUG] When navigation guard dialog for save is open, pressing `escape` causes confirm behavior
When you forget to save and try to navigate away, if you press escape, this should be a `cancel` operation and not a `confirm` operation.

The effect is that `escape` makes you lose your changes when you probably wanted to abort the navigation.

### PR DESCRIPTION
**Pull request by BryonLewis**
Just some really minor UI fixes to reduce the backlog

- Fixed the `annotator.js` references to `geo_actiton_select` and the owner
- Fixes #409 - changes the text and allows the user to prevent themselves from exiting the current view
- Fixes #278 - just a text change which shouldn't be used as a key anywhere else
- Fixes #388 - remove the pencil icon while in editing mode, left the others so you know what type you are drawing

### CODE REVIEW

File: client/viame-web-common/components/Viewer.vue [hunk 1]
```diff
@@ -287,14 +287,11 @@ export default defineComponent({
       if (pendingSaveCount.value > 0) {
         result = await prompt({
           title: 'Save Items',
-          text: 'There is unsaved data, what would you like to do?',
-          positiveButton: 'Save',
-          negativeButton: 'Discard',
+          text: 'There is unsaved data, would you like to continue or cancel and save?',
+          positiveButton: 'Continue',
+          negativeButton: 'Cancel',
```
Comment (subdavis) [inline client/viame-web-common/components/Viewer.vue:292]: I still think cance/continue is ambiguous, and people probably won't read the text.

* Continue leaving, or continue editing?
* Cancel edits or cancel leaving?

How about something more explicit?

Screenshot from 2020-11-13 16-23-21

**Review by subdavis — CHANGES_REQUESTED** [review]
I still think that dialog is ambiguous.  See my suggestion.

Pulled and tested, everything works great

**Review by subdavis — APPROVED** [review]
Lgtm
