### PR TITLE
Client/bugfix run pipelines

### LINKED ISSUE #422: [BUG] [Regression] Run Pipeline button enabled even when nothing is selected
In a folder that is not a dataset when nothing is selected, the button should not be enabled.

### PR DESCRIPTION
**Pull request by subdavis**
fixes #422

### CODE REVIEW

File: client/viame-web-common/components/RunPipelineMenu.vue [hunk 1]
```diff
@@ -43,10 +43,13 @@ export default defineComponent({
     });
 
     const pipelinesNotRunnable = computed(() => (
-      props.selectedDatasetIds.length > 1 || pipelines.value === null
```
Comment (subdavis) [inline client/viame-web-common/components/RunPipelineMenu.vue:46]: As best I can tell, this was just an uncaught typo.  The logic makes no sense otherwise.

Comment (BryonLewis) [reply client/viame-web-common/components/RunPipelineMenu.vue:46]: Might of been to prevent a user from running pipelines on multiple datasets, but looks like a mistake.

**Review by BryonLewis — APPROVED** [review]
Pulled and tested and looks good.
