### PR TITLE
Fix location errors

### LINKED ISSUE #187: Adjust  Vuex state location in AnnotationViewer
The location viewer in the Annotation Editor/Viewer is set based off an existing location in the store.  That is fine if you navigate to the data object and then click on "Data" to go back.  If you are given a link directly or refresh the page manually the Data location link breaks and sends you back to the base location of the server.

The information is already in there because we need the folder location to get the data.  I just suggest modifying how we retrieve and set the location if it doesn't exist to the proper one.

This would allow the user to provide links and when they the receiver of the link clicks on data they will be placed in the relevant folder.

### LINKED ISSUE #188: Breadcrumb clicking is broken
While in a subfolder that has clicking on the breadcrumb to go back up a folder will cause an error:
image
Looks like an issue with the type of location object we are supplying to the FileManager.

### PR DESCRIPTION
**Pull request by BryonLewis**
Fixes #187 
Fixes #188 

The location in the vuex state wasn't working properly with the breadcrumb bar in the file browser.  It required a click on which it would error and then a second click where it would finally change the page.  I updated Home.vue to get rid of the mapping of a location object while also having a computed location object.  This fix should make it work for all of the breadcrumb items as well as  utilizing the back/forward in the browser.

Additionally to this I modified the `Viewer.vue` to check and see if the state `location` variable is set.  If you navigate directly to an annotation link or if you refresh the page you reset and lose that `location` variable and when you click "Data" in the NavBar it takes you back to the root of girder.  I've updated it so it checks and sees if it has a location and if it doesn't it will calculate it from the returned girder folder and set the location as the parent folder.  This means that even refreshing or when provided a link clicking data should return you to the parent folder.  

To do this I added some items to the `GirderModel` interface to support `parentCollection, parentId`.  The data returned from `getFolder` should contain that data considering our annotations are always inside of a folder, although other times it won't have it if we are utilizing the breadcrumb.

### CODE REVIEW

File: client/src/views/Home.vue [hunk 1]
```diff
@@ -80,15 +81,13 @@ export default {
     },
   },
   created() {
-    this.location_ = getLocationFromRoute(this.$route);
-    this.setLocation(this.location_);
+    this.setLocation(getLocationFromRoute(this.$route));
```
Comment (subdavis) [inline client/src/views/Home.vue:84]: I think ideally one would use https://github.com/vuejs/vuex-router-sync rather than trying to remember to `setLocation` in every view that may get loaded

File: client/src/views/Home.vue [hunk 2]
```diff
@@ -80,15 +81,13 @@ export default {
...
     this.notificationBus.$on('message:job_status', this.handleNotification);
   },
   beforeDestroy() {
     this.notificationBus.$off('message:job_status', this.handleNotification);
   },
   beforeRouteUpdate(to, from, next) {
-    this.location_ = getLocationFromRoute(to);
     next();
   },
```
Comment (subdavis) [inline client/src/views/Home.vue:92]: Looks like you can remove this whole function.  `next()` is the default behavior.

FWIW, if you needed to do something like this, `vuex-router-sync` is what you want.  This is basically what that plugin is designed for.
