### PR TITLE
Use track lists directly #193

### LINKED ISSUE #193: Allow use of Track objects in computed properties
It turns out I was completely wrong about whether or not it's OK to return a Track from a computed function.   Computed return values are immutable, so they only have shallow reactivity.

All the places where we unwrap the properties from a track into something else is (mostly) pointless and can be removed.
That's sort of nice, because now anything that needs a list of track-like data can just have access to the whole track.

In practice I think this means we can keep trackMap  as an implementation detail of useTrackStore  and won't have to export it at all.

(except for useModeManager where trackIds associated with user events need to be dereferenced)

### PR DESCRIPTION
**Pull request by subdavis**
Semi-invasive update, generally reduces complexity, drops about 50 LoC.

Fixes #193

### CODE REVIEW

File: client/src/views/TrackViewer/Layers.vue [hunk 1]
```diff
@@ -101,47 +101,45 @@ export default defineComponent({
...
+            const trackFrame = {
+              selected: (selectedTrackId === track.trackId),
+              editing: editingTrack,
+              trackId: track.trackId,
+              features,
+              confidencePairs: track.getType(),
+            };
+            frameData.push(trackFrame);
+            if (frameData[frameData.length - 1].selected && (editingTrack || featurePointing)) {
+              editingTracks.push(trackFrame);
```
Comment (BryonLewis) [inline client/src/views/TrackViewer/Layers.vue:134]: Think it would make sense in the future to just refactor this to pass directly to the drawing layers the filteredTracks and the `selectedTrackId/editingTrack props`?  Then when `editingTrack` is true we just do a `findIndexOf` instead of iterating over the entire filtered track list and pass that frameData to the editing layer.  It would avoid this data organizational loop of the filtered tracks at the expense of giving the layers more information and access to the Track items.

**Comment by subdavis** [comment]
> then immediately unwraps it in useTrackFilter for the checkedTrackIds reference object.

The old line (before I added unwrapping) is here:

```js
const checkedTrackIds = ref(Array.from(sortedTrackIds.value));
```

That `Array.from()` also [invokes a shallow copy look](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from), so the performance is `O(N)` either way.

We could convert `checkedTrackIds` to `checkedTracks` but we would still need to create the shallow copy.

**Comment by BryonLewis** [comment]
> That `Array.from()` also [invokes a shallow copy loop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from), so the performance is `O(N)` either way. I don't know how much heavier hashmap lookup is compared to simple copying, but it may be significant.

Thanks for the explanation.  I don't know either whether it is better to do the `getTrack` each iteration of a loop for the consumers of the data or to do it ahead of time in the `.map` function on `sortedTracks`.  Again I don't notice any problem as of now with 2800+ tracks.
