### PR TITLE
Enhancement/image cache

### LINKED ISSUE #13: Seeking backward doesn't work, prefetching doesn't wait for frames to load.
Pre-fetching only works when playing the video forward in time.  However, when doing an annotation, a user will want to find the beginning of the track, which can involve seeking backward.

* Find a fish you want to track
* grab the track head and drag backward to look for the fish's first appearance.

result: lots of waiting for an image to appear.

### PR DESCRIPTION
**Pull request by BryonLewis**
Fixes #13 
Improves the image caching system to prevent the playing of black/blank frames.
Adds in a variable `playCache` which requires a number of seconds to be cached before continuing with playback.  If the images aren't available a loading screen will display.
Adds in a variable `cacheSeconds` specifying the number of seconds to cache images which is then subdivided between forward cache and backwards cache using `frontBackRatio`
`Image.complete` is [unreliable](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/complete) in the sense that it will be marked as true when no src has been set or the src is empty.  I'm using my own `image.cached` boolean attached to loaded images to track caching.

The caching system will now clear pending items itself after a seek or a drag backwards.  It will also prioritize the current frame when dragging or seeking instead of waiting for the cache to load the frame.  You can still get black frames when seeking, but they should resolve faster.

For testing purposes I would suggest creating a custom network profile in the chrome network tab and set the download speed to ~73Mbps.  This works fairly well with the Ehu test data.  Just enough where it isn't painful to load but will still cause some loading during typical playback.

### CODE REVIEW

File: client/src/components/annotators/ImageAnnotator.vue [hunk 1]
```diff
@@ -12,8 +12,23 @@ export default {
...
+  data() {
+    return {
+      loadingVideo: false,
+    };
+  },
   created() {
+    this.playCache = 1; // seconds required to remain playing (should be less that cache seconds)
+    this.cacheSeconds = 3; // seconds to cache
+    this.frontBackRatio = 0.90; // 90% forward frames, 10% backward frames when caching
+    // playCache needs to be less than the adjusted cache seconds to work properly
```
Comment (subdavis) [inline client/src/components/annotators/ImageAnnotator.vue:24]: I don't understand this comment.

File: client/src/components/annotators/ImageAnnotator.vue [hunk 2]
```diff
@@ -12,8 +12,23 @@ export default {
...
+    if (this.playCache > this.cacheSeconds * this.frontBackRatio) {
+      const difference = (this.playCache - (this.cacheSeconds * this.frontBackRatio));
+      this.cacheSeconds = Math.ceil(this.cacheSeconds + difference);
+    }
+    if (this.frontBackRatio > 1 || this.frontBackRatio < 0) {
+      this.frontBackRatio = 1.0;
+    }
```
Comment (subdavis) [inline client/src/components/annotators/ImageAnnotator.vue:31]: You explicitly set it to `0.9`on line 23, then put a conditional here.  I don't understand how the value could have changed in the middle.

File: client/src/components/annotators/ImageAnnotator.vue [hunk 3]
```diff
@@ -97,37 +114,104 @@ export default {
           this.syncedFrame = this.maxFrame;
           return;
         }
+        if (!this.imgs[this.frame].cached || this.loadingVideo) {
+          this.frame -= 1;
+          this.loadingVideo = true;
+          return;
+        }
```
Comment (subdavis) [inline client/src/components/annotators/ImageAnnotator.vue:121]: A general description of what this function does would be cool.  I don't understand it, but it seems like you do.

File: client/src/components/annotators/ImageAnnotator.vue (hunk 1 above)
Comment (BryonLewis) [reply client/src/components/annotators/ImageAnnotator.vue:24]: There is the standard cache, which is how many seconds of images it should download represented by `cacheSeconds`
There is the `playCache` this cache looks forward X seconds from the current frame and sees if the frames are all loaded.  If not it will display a Loading spinner.
The `frontBackRatio` resolves the part of the issue of backwards seeking.  If you jump forward using a the mouse it will dedicate a certain portion to caching data behind the current frame.

File: client/src/components/annotators/ImageAnnotator.vue [hunk 4]
```diff
@@ -97,37 +114,104 @@ export default {
...
+      const cachedFrames = this.cacheSeconds * this.frameRate;
+      const min = Math.floor(Math.max(0, frame - cachedFrames * (1 - this.frontBackRatio)));
+      const max = Math.ceil(Math.min(frame + this.frontBackRatio * cachedFrames, this.maxFrame));
+      const frameDiff = Math.abs(this.frame - this.lastFrame);
+      const prevFrame = (this.frame < this.lastFrame);
       this.pendingImgs.forEach((imageAndFrame) => {
-        if (imageAndFrame[1] < frame || imageAndFrame[1] > max) {
+        // the current loading cache nees to be wiped out if we seek forward, backwards or
+        // if we are out of the current range of the cache
+        if (imageAndFrame[1] < min || imageAndFrame[1] > max || frameDiff > 2 || prevFrame) {
```
Comment (subdavis) [inline client/src/components/annotators/ImageAnnotator.vue:137]: This is a great comment.

File: client/src/components/annotators/ImageAnnotator.vue (hunk 2 above)
Comment (BryonLewis) [reply client/src/components/annotators/ImageAnnotator.vue:31]: This wasn't a complete PR thing I wanted the ability to change the cache to see what would work best for our purposes.  That just ensures that I don't  go outside my bounds.  I'm still in the testing phase of what I want to use for the value or if it should be exposed.

File: client/src/components/annotators/ImageAnnotator.vue [hunk 5]
```diff
@@ -97,37 +114,104 @@ export default {
...
+          resolve(frame);
+        };
+      });
+    },
+    /**
+     * Caches a new range of frames to load
+     * @param {int} min - lower bound frame number for caching
+     * @param {int} max - upper bound frame number for caching
+     */
+    cacheNewRange(min, max) {
```
Comment (subdavis) [inline client/src/components/annotators/ImageAnnotator.vue:174]: It looks like the cache loads back to front, starting at currentFrame - (0.1*cachesize).  Would it make a difference to load from the current frame outward sort of jumping back and fourth?

Comment (BryonLewis) [reply client/src/components/annotators/ImageAnnotator.vue:174]: that's why it's a draft, one of my ideas was loading from the current frame out.  I haven't implemented that yet.

File: client/src/components/annotators/ImageAnnotator.vue [hunk 6]
```diff
@@ -97,37 +114,104 @@ export default {
...
+     * Wraps loading of a single frame in a promise
+     * @param {int} frame number to be loaded
+     * @returns {Promise} resolves when the image from the frame is loaded
+     */
+    loadFrame(frame) {
+      return new Promise((resolve) => {
+        const img = new Image();
+        img.crossOrigin = 'Anonymous';
+        img.src = this.imageUrls[frame];
+        this.imgs[frame] = img;
```
Comment (subdavis) [inline client/src/components/annotators/ImageAnnotator.vue:161]: I haven't dealt with a lot of browser caching myself, so this may be a dumb question:

Why do you have to actually keep a reference to the returned image?  Isn't it enough to just make the request and then destroy the DOM element, and rely on the browser network cache to hit the next time the request is made?

Comment (BryonLewis) [reply client/src/components/annotators/ImageAnnotator.vue:161]: Cache might be a bad term for what we are actually doing.  We are loading the images so that they can be played back in sequence while avoiding async calls if possible.  In other instances that aren't as time dependent, I've loaded the images I know would be needed then discarded the image objects afterwards.
geoJS is expecting an image object each frame when it renders.  It is utilizing some of the stuff contained within a loaded image object such as `img.width` and `img.height` as well as `img.src`.  We could recreate these image objects before the frame is drawn but the assignment of an image.src **I think** would kick it to the event loop even if it is in the browser cache, so depending on framerate of the playback you may get black flickering (what I guess geoJS draws if the `Image.src` is invalid).

File: client/src/components/annotators/ImageAnnotator.vue (hunk 3 above)
Comment (BryonLewis) [reply client/src/components/annotators/ImageAnnotator.vue:122]: Description was added for the function and this section as well.
